---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- 开发:
    - Github:
        - abbr: GH
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/github.svg
          href: https://github.com/iceyear

- 社交:
    - 联邦宇宙:
        - abbr: FD
          href: https://starry.ml/@iceyear

- 网站:
    - IY引导页:
        - abbr: IY
          href: https://iceyear.ml/
